# Generated by Django 5.0.1 on 2024-01-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
