# Generated by Django 5.0.1 on 2024-01-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_image_image_height_image_image_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpIconContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Help Icon Content',
            },
        ),
    ]
