# Generated by Django 5.0.1 on 2024-01-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_helpiconcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpiconcontent',
            name='content',
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
