# Generated by Django 5.0.1 on 2024-01-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_image_image_alter_image_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridColumns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_columns', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Grid Columns',
            },
        ),
    ]
