# Generated by Django 5.0.1 on 2024-01-29 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_gridcolumns'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=128)),
                ('ip_address', models.CharField(max_length=40)),
                ('view_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.image')),
            ],
        ),
    ]
