# Generated by Django 5.0.1 on 2024-01-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_imageview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageview',
            name='ip_address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='imageview',
            name='session_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
