# Generated by Django 5.0.1 on 2024-01-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_image_video_alter_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name_plural': 'Contents (Images and Videos)'},
        ),
        migrations.AddField(
            model_name='image',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='public/images/'),
        ),
    ]
